### PR TITLE
AirSwap V3 subgraph

### PR DESCRIPTION
**Pull request by geewynn**
This is the first version of the airswap subgraph.This subgraphs indexes all emitted events and schema built to support building an analytic dashboard similar to the dune dashboard.

### CODE REVIEW

**Comment by dmosites** [comment]
Possible to pull ABIs in from packages e.g. `@airswap/registry/build/contracts/Registry.sol/Registry.json`?

**Comment by dmosites** [comment]
Is the `generated` folder like a build? Does it need to be included in the repository or can be generated locally?

**Comment by geewynn** [comment]
> Is the `generated` folder like a build? Does it need to be included in the repository or can be generated locally?

It can be generated locally before build but i added this here because i wanted a single source of truth and also because i had to edit some errors that i encountered in the generated folder before deploying to rinkeby

**Comment by geewynn** [comment]
> Possible to pull ABIs in from packages e.g. `@airswap/registry/build/contracts/Registry.sol/Registry.json`?

I'm not sure but the abi's can be downloaded from the packages into that folder. You can look at this

https://thegraph.com/docs/en/developer/create-subgraph-hosted/#getting-the-ab-is

**Comment by dmosites** [comment]
> > Is the `generated` folder like a build? Does it need to be included in the repository or can be generated locally?
> 
> It can be generated locally before build but i added this here because i wanted a single source of truth and also because i had to edit some errors that i encountered in the generated folder before deploying to rinkeby

Does generated code change at all depending on the network? What errors did you encounter?

**Comment by geewynn** [comment]
> > > Is the `generated` folder like a build? Does it need to be included in the repository or can be generated locally?
> > 
> > 
> > It can be generated locally before build but i added this here because i wanted a single source of truth and also because i had to edit some errors that i encountered in the generated folder before deploying to rinkeby
> 
> Does generated code change at all depending on the network? What errors did you encounter?

No, the generated code doesn't change. It stays the same for all the network.

**Review by dmosites — APPROVED** [review]

**Pull request merged**
